MEX       = mex
MUMPS_DIR = $(HOME)/MUMPS_4.8.0

LMETISDIR = /home/afevre/metis-4.0
LMETIS = -L$(LMETISDIR) -lmetis
LPORDDIR = $(MUMPS_DIR)/PORD/lib
LPORD = -L$(LPORDDIR) -lpord
LORDERINGS = $(LPORD) $(LMETIS)

LIBSEQ  = -L$(MUMPS_DIR)/libseq -lmpiseq

LIBBLAS = -lblas

LIBFORT = /usr/lib/libf95.a /usr/lib/libgcc.a 

OPTC    = -O 

